publicIp: 127.0.0.1

# Persistent Storage is optional, you can leave the keys out.
# Example:
#persistentVolumeClaim:
#  size:
#    varData: "100Gi"
#    varDataMiner: "1Gi"
#  create:
#    varData: true
#    varDataMiner: true
#  storageClass:
#    varData: "cstor-csi"
#    varDataMiner: "cstor-csi"

image:
  pullPolicy: IfNotPresent
  repository: quay.io/team-helium/validator
  # tag: miner-amd64_testnet_val0.1.82 # testnet
  tag: miner-amd64_validator1.0.1 # mainnet

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
resources:
  limits:
    cpu: 3500m
  #   memory: 128Mi
  requests:
    cpu: 1300m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

service:
  setLoadBalancerIP: true
  setExternalIp: false
  externalTrafficPolicy: Cluster

serviceAnnotations: {}
# You might need annotations for your ingress / service to pin the right IP, e.g.
# serviceAnnotations:
#   "metallb.universe.tf/address-pool": "helium-validators-01"

