apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "helium-validator.fullname" . }}"
  labels:
    {{- include "helium-validator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: helium-validator
      {{- include "helium-validator.labels" . | nindent 6 }}
  template:
    metadata:
      name: "{{ include "helium-validator.fullname" . }}"
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: helium-validator
        {{- include "helium-validator.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 120
      restartPolicy: Always
      {{- if not (kindIs "invalid" .Values.serviceAccountName) -}}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: helium-miner-val
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env:
        - name: NAT_EXTERNAL_IP
          value: "{{ .Values.publicIp }}"
        - name: NAT_INTERNAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 2154
          name: helium
        - containerPort: 4467
          name: miner2
        - containerPort: 8080
          name: miner3
        - containerPort: 35981
          name: miner4
        - containerPort: 4369
          name: epmd1 
        livenessProbe:
          tcpSocket:
            port: 2154
          initialDelaySeconds: 180
          periodSeconds: 180
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        {{- if not (kindIs "invalid" .Values.persistentVolumeClaim.storageClass.varData) }}
        - name: helium-validator-var-data
          mountPath: /var/data
        {{- end }}
        {{- if not (kindIs "invalid" .Values.persistentVolumeClaim.storageClass.varDataMiner) }}
        - name: helium-validator-var-data-miner
          mountPath: /var/data/miner
        {{- end }}
      volumes:
        {{- if not (kindIs "invalid" .Values.persistentVolumeClaim.storageClass.varData) }}
        - name: {{ include "helium-validator.fullname" . }}-var-data
          persistentVolumeClaim:
            claimName: helium-validator-var-data
        {{- end }}
        {{- if not (kindIs "invalid" .Values.persistentVolumeClaim.storageClass.varDataMiner) }}
        - name: {{ include "helium-validator.fullname" . }}-var-data-miner
          persistentVolumeClaim:
            claimName: helium-validator-var-data-miner
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

