{{ if .Values.persistentVolumeClaim.create.varDataMiner -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "helium-validator.fullname" . }}-var-data-miner"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ .Values.persistentVolumeClaim.storageClass.varDataMiner }}"
  resources:
    requests:
      storage: "{{ .Values.persistentVolumeClaim.size.varDataMiner }}"
{{ end -}}

