{{- if .Values.PersistentVolumeClaim.create.varDataMiner -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "helium-validator.fullname" . }}-var-data-miner"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ .Values.storageClass.name.varDataMiner }}"
  resources:
    requests:
      storage: "{{ .Values.PersistentVolumeClaim.size.varDataMiner }}"
{{- end -}}

