apiVersion: v1
kind: Service
metadata:
  name: "{{ include "helium-validator.fullname" . }}"
  labels:
    {{- include "helium-validator.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.publicIp }}"
  externalTrafficPolicy: Cluster
  ports:
    - name: helium-validator
      port: 2154
      targetPort: 2154
      protocol: TCP
  selector:
    app.kubernetes.io/name: "helium-validator"

